# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200, verbose_name='tema')),
                ('descricao', models.TextField(max_length=500, verbose_name='descrição')),
                ('abertura_atividade', models.DateTimeField(verbose_name='abertura')),
                ('encerramento_atividade', models.DateTimeField(verbose_name='encerramento')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='local de realização')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('local', models.CharField(max_length=200, verbose_name='local')),
                ('abertura_evento', models.DateField(verbose_name='abertura do evento')),
                ('encerramento_evento', models.DateField(verbose_name='encerramento do evento')),
                ('abertura_inscricoes', models.DateField(verbose_name='abertura das inscrições')),
                ('encerramento_inscricoes', models.DateField(verbose_name='encerramento das inscrições')),
                ('limite_inscricoes', models.IntegerField(default=100, verbose_name='limite de inscrições')),
                ('apresentacao', models.TextField(blank=True, null=True, verbose_name='apresentação')),
                ('publico_alvo', models.TextField(blank=True, null=True, verbose_name='público alvo')),
                ('programacao', models.TextField(blank=True, null=True, verbose_name='programação')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='descrição')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
            ],
            options={
                'verbose_name': 'tipo de atividade',
                'verbose_name_plural': 'tipos de atividades',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.TipoAtividade'),
        ),
    ]
