# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='tipo_atividade',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='TipoAtividade',
        ),
    ]
