# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20170327_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='abertura_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='abertura_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='apresentacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='encerramento_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='encerramento_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='limite_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='programacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publico_alvo',
        ),
        migrations.AddField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateTimeField(null=True, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.CharField(max_length=200, null=True, verbose_name='nome'),
        ),
    ]
