# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20170327_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(max_length=50, null=True, verbose_name='palavras chave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=60, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=600, null=True, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(max_length=600, null=True, verbose_name='logotipo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.CharField(max_length=2, null=True, verbose_name='uf'),
        ),
    ]
